AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  SourceBucket:
    Type: String
    Description: Name of the existing source S3 bucket. An IAM role will be automatically created to limit the scope of the Lambda function. 
    
Resources:
  sqs:
    Type: AWS::SQS::Queue

  s3golang:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Tracing: Active
      Runtime: go1.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt sqs.Arn
            BatchSize: 1
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
              Resource: !Sub "arn:aws:s3:::${SourceBucket}*"
      Environment:
        Variables:
          appname: 'go-s3-lambda'
          awsbucket: 'go-s3-lambda'
          awsregion: 'eu-west-1'